'''
Created on Mar 21, 2016

@author: loongchan
'''
###### GENERAL STUFF ######
DEBUG = True

###### USED FOR SLAVE NAME STUFF ######
DEFAULT_GLOBAL_COUNTER_FILENAME = '/home/cloud/cmpt733_global_counter.txt'
BASE_SLAVE_NAME = 'dlw-Slave'
SLAVE_NAMING_REGEX = BASE_SLAVE_NAME+'(\d+)'

###### USED FOR UPSIZING STUFF ######
DEFAULT_LOCAL_HOSTS_FILENAME = '/home/cloud/hosts'
DEFAULT_DESTINATION_HOSTS_FILENAME = '/etc/hosts'
DEFAULT_LOCAL_SLAVES_FILENAME = '/home/cloud/slaves'
DEFAULT_DESTINATION_SLAVES_FILENAME = '/home/hduser/hadoop-2.7.0/etc/hadoop/slaves'
DEFAULT_LOCAL_HOSTNAME_FILENAME = '/home/cloud/hostname'
DEFAULT_DESTINATION_HOSTNAME_FILENAME = '/etc/hostname'
SLAVES_FILE_USER = 'hduser'
HOSTS_FILE_USER = 'root'
MASTER_IP = '199.60.17.143'

###### DOWNSIZING STUFF ######
MINIMUM_DATANODE_SIZE = 2 
REPORT_DATANODE_STATUS_STARTING_REGEX = 'Name:\s\d+\.\d+\.\d+\.\d+.*\('
DEFAULT_LOCAL_EXCLUDES_FILENAME = '/home/cloud/excludes'
DEFAULT_DESTINATION_EXCLUDES_FILENAME = '/home/hduser/hadoop-2.7.0/etc/hadoop/excludes'

###### SSH RETRY MAX TIME #####
MAX_SLEEP_TIME = 20

###### STUFF FOR CREATING MACHINE ######
TEMPLATEID = 'f276b844-a0a4-457e-a1f5-20b669ea5ea7'
SERVICEOFFERINGID = '294442fc-cb8e-47aa-b768-ca0f95054b95'
ZONEID = 'c687b45d-2822-43bc-a061-3399e92581d0'