'''
Created on Mar 21, 2016

@author: loongchan
'''
###### GENERAL STUFF ######
DEBUG = True

###### USED FOR SLAVE NAME STUFF ######
DEFAULT_GLOBAL_COUNTER_FILENAME = '/home/cloud/cmpt733_global_counter.txt'
BASE_SLAVE_NAME = 'dlw-Slave'
SLAVE_NAMING_REGEX = BASE_SLAVE_NAME+'(\d+)'

###### USED FOR UPSIZING STUFF ######
DEFAULT_LOCAL_HOSTS_FILENAME = '/home/cloud/hosts'
DEFAULT_DESTINATION_HOSTS_FILENAME = '/etc/hosts'
DEFAULT_LOCAL_SLAVES_FILENAME = '/home/cloud/slaves'
DEFAULT_DESTINATION_SLAVES_FILENAME = '/home/hduser/hadoop-2.7.0/etc/hadoop/slaves'
DEFAULT_LOCAL_HOSTNAME_FILENAME = '/home/cloud/hostname'
DEFAULT_DESTINATION_HOSTNAME_FILENAME = '/etc/hostname'
SLAVES_FILE_USER = 'hduser'
HOSTS_FILE_USER = 'root'
MASTER_IP = '199.60.17.143'

###### DOWNSIZING STUFF ######
MINIMUM_DATANODE_SIZE = 2 
REPORT_DATANODE_STATUS_STARTING_REGEX = 'Name:\s\d+\.\d+\.\d+\.\d+.*\('
DEFAULT_LOCAL_EXCLUDES_FILENAME = '/home/cloud/excludes'
DEFAULT_DESTINATION_EXCLUDES_FILENAME = '/home/hduser/hadoop-2.7.0/etc/hadoop/excludes'

###### SSH RETRY MAX TIME #####
MAX_SLEEP_TIME = 20

###### HADOOP METRIC INFO #####
METRIC_CACHE_MIN_SECONDS = 3
METRIC_PORT = '8088'

###### STUFF FOR CREATING MACHINE ######
TEMPLATEID = '5c1fff33-43ab-4b74-9dc0-a766bb2eb7fc'
SERVICEOFFERINGID = '294442fc-cb8e-47aa-b768-ca0f95054b95'
ZONEID = 'c687b45d-2822-43bc-a061-3399e92581d0'

###### LOAD BALANCER PARAMETERS ######
INITIAL_PATIENCE = 50
SLEEP = 2
BIG_SLEEP = 30
QUEUE_WEIGHT = 4
MEMORY_WEIGHT = 2
CPU_WEIGHT = 1
HIGH_STATE_PERCENTAGE = 0.75
LOW_STATE_PERCENTAGE = 0.25
THRESHOLD = 0.8
